var N = null;var sourcesIndex = {};
sourcesIndex["cli"] = {"name":"","files":["cli.rs"]};
sourcesIndex["grpc"] = {"name":"","files":["grpc.rs"]};
sourcesIndex["gui_remote"] = {"name":"","files":["gui_remote.rs"]};
sourcesIndex["guppy_controller"] = {"name":"","dirs":[{"name":"motion_planner","files":["continuous_motion_planner.rs","mod.rs","trajectory_motion_planner.rs"]}],"files":["arm_config.rs","arm_controller.rs","arm_driver.rs","collision_handler.rs","lib.rs"]};
sourcesIndex["guppy_grpc"] = {"name":"","files":["grpc_client.rs","grpc_controller.rs","lib.rs"]};
sourcesIndex["guppy_ui"] = {"name":"","files":["lib.rs","visualizer.rs"]};
sourcesIndex["motion_planner"] = {"name":"","files":["motion_planner.rs"]};
sourcesIndex["simulator"] = {"name":"","files":["simulator.rs"]};
createSourceSidebar();
